# Site settings
title: Recipes
email: your-email@domain.com
description: Un site de recettes qui utilise jekyll et markdown
# use this if you're using a /folder
baseurl: ""
url: "https://recipe.home.hatrix.fr"
twitter_username: ""
github_username: ""

# Build settings
markdown: kramdown

collections:
  components:
    output: true
  recipes:
    output: true

gems: ['jekyll-lunr-js-search']

lunr_search:
     excludes: [rss.xml, atom.xml]
     min_length: 3
     stopwords: "stopwords.txt"

mini_magick:
    thumbnail:
        source: _recipes
        destination: images/thumbnail
        resize: "400x400"
    medium:
        source: _recipes
        destination: images/medium
        resize: "800x800"
    large:
        source: _recipes
        destination: images/large
        resize: "1500x1500"

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'recipe_template.md']
